# Generated by Django 4.2.17 on 2025-05-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Google_Sheets_Data',
            fields=[
                ('PK_Unique', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('UserID', models.IntegerField(blank=True, null=True)),
                ('Username', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Food', models.FloatField(blank=True, null=True)),
                ('Stuff', models.FloatField(blank=True, null=True)),
                ('Leisure', models.FloatField(blank=True, null=True)),
                ('Automatic_withdrawal', models.FloatField(blank=True, null=True)),
                ('Automatic_withdrawal_com', models.CharField(blank=True, max_length=255, null=True)),
                ('SMBC_payments', models.FloatField(blank=True, null=True)),
                ('SMBC_card_comments', models.CharField(blank=True, max_length=300, null=True)),
                ('Utility', models.FloatField(blank=True, null=True)),
                ('Details_utility', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_amount', models.FloatField(blank=True, null=True)),
                ('Name_sheet', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Google_Sheets_Data',
            },
        ),
    ]
